### PR TITLE
Fix xhr and fetch logging in Cypress 13+ to use props sub-key of consoleProps

### LINKED ISSUE #209: cy:xhr logs show "undefined" in Cypress 13
Behaviour with Cypress 12, XHR logs show only failed requests:

```
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        12.17.4                                                                        │
  │ Browser:        Edge 116 (headless)                                                            │
  │ Node Version:   v18.17.1 (/usr/local/bin/node)                                                 │
...
  │ Experiments:    experimentalMemoryManagement=true                                              │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  fct-activity-channel.feature                                                   (1 of 16)
  cypress:server:browsers browsers.kill called with no active instance +0ms
  cypress:server:browsers getBrowserLauncher { browser: { name: 'edge', family: 'chromium', channel: 'stable', displayName: 'Edge', version: '116.0.1938.62', path: 'edge', minSupportedVersion: 79, majorVersion: '116', isHeadless: true, isHeaded: false } } +1ms
  cypress:server:browsers opening browser { name: 'edge', family: 'chromium', channel: 'stable', displayName: 'Edge', version: '116.0.1938.62', path: 'edge', minSupportedVersion: 79, majorVersion: '116', isHeadless: true, isHeaded: false } +5ms
  cypress:server:browsers browser opened +1s
  Activity Channel
          cy:xhr ✘  GET https://isda-isda-frontend-test-8084-comment-ltiuxb.dev.i.nakhoda.ai/api/v1/subAccounts/018a5010-d45c-4c6b-43eb-5e40cddfbc8f/negotiations/018a5010-047d-2638-f62b-a506137c3fd6/preview
```

Behaviour with Cypress 13:

```
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        13.1.0                                                                         │
  │ Browser:        Edge 116 (headless)                                                            │
  │ Node Version:   v18.17.1 (/usr/local/bin/node)                                                 │
...
  │ Experiments:    experimentalMemoryManagement=true                                              │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

  Running:  fct-activity-channel.feature                                                   (1 of 16)
  cypress:server:browsers browsers.kill called with no active instance +0ms
  cypress:server:browsers getBrowserLauncher { browser: { name: 'edge', family: 'chromium', channel: 'stable', displayName: 'Edge', version: '116.0.1938.69', path: 'edge', minSupportedVersion: 79, majorVersion: '116', isHeadless: true, isHeaded: false } } +0ms
  cypress:server:browsers opening browser { name: 'edge', family: 'chromium', channel: 'stable', displayName: 'Edge', version: '116.0.1938.69', path: 'edge', minSupportedVersion: 79, majorVersion: '116', isHeadless: true, isHeaded: false } +4ms
  cypress:server:browsers browser opened +2s
  Activity Channel
          cy:xhr ❖  undefined undefined
          cy:xhr ❖  undefined undefined
          cy:xhr ❖  undefined undefined
          cy:xhr ❖  undefined undefined
          cy:xhr ❖  undefined undefined
          cy:xhr ❖  undefined undefined
          cy:xhr ❖  undefined undefined
          cy:xhr ❖  undefined undefined
          cy:xhr ❖  undefined undefined
          cy:xhr ❖  undefined undefined
          cy:xhr ❖  undefined undefined
          cy:xhr ❖  undefined undefined
          cy:xhr ❖  undefined undefined
...etc
```

Setup:

```ts
import installLogsCollector from 'cypress-terminal-report/src/installLogsCollector'

// Logs Cypress output to STDOUT for CI logs when using cypress run
installLogsCollector({
  collectTypes: ['cy:log', 'cy:xhr', 'cy:request', 'cy:intercept', 'cy:command'],
  debug: false,
  enableExtendedCollector: false,
  filterLog([type, message, severity]) {
    // Always print steps
    if (type === 'cy:command') {
      return message.startsWith('step\t')
    }

    // Always print cy:log
    if (type === 'cy:log') {
      return true
    }

    if (type === 'cy:xhr' && severity === 'error' && message.endsWith(' - ABORTED')) {
      // Don't show ABORTED requests
      return false
    }

    return ['error', 'warning'].includes(severity)
  },
})

```

### PR DESCRIPTION
**Pull request by matmannion**
Fixes #209

Supports both Cypress <12 and Cypress 13+ format for `consoleProps` for xhr and fetch logs.

### CODE REVIEW

**Comment by archfz** [comment]
Looks good. Could you check why tests are failing? I quickly check but it is not clear to me why the messages changed for some of the log types.

File: src/collector/LogCollectCypressXhr.js [hunk 1]
```diff
@@ -12,17 +12,20 @@ module.exports = class LogCollectCypressXhr {
...
 
   register() {
-    const formatXhr = (options) =>
-      (options.renderProps.wentToOrigin ? '' : 'STUBBED ') +
-      options.consoleProps.Method + ' ' + options.consoleProps.URL;
+    // In Cypress 13+ this is under an extra props key
+    const consoleProps = (options) => options.consoleProps && options.consoleProps.props ? options.consoleProps.props : options.consoleProps
+
+    const formatXhr = (options) => (options.alias !== undefined ? '(' + options.alias + ') ' : '') +
+      (consoleProps(options)["Request went to origin?"] !== 'yes' ? 'STUBBED ' : '') +
```
Comment (hans2520) [inline src/collector/LogCollectCypressXhr.js:19]: Just trying to help get the fix for the breaking tests identified -- Is the fact that `(options.renderProps.wentToOrigin ? '' : 'STUBBED ')` no longer present cause a break for Cypress < 12?

Also, completely blind question, so forgive my ignorance if it is showing -- anything in this project preventing the use of optional chain operators, i.e. instead of `options.consoleProps && options.consoleProps.props` you could have `options.consoleProps?.props`

Comment (archfz) [reply src/collector/LogCollectCypressXhr.js:19]: That could be one of the reasons indeed.

Optional chaining was introduced in node version 14. We currently require cypress > 10 for current version, but that doesn't require node >= 14 yet. If we would start using it we would need to declare that node >= 14 is required, in docs and in package.json. I would say leave it for now.

Comment (matmannion) [reply src/collector/LogCollectCypressXhr.js:19]: Good shout, have reverted this change

**Comment by archfz** [comment]
Released in 5.3.4 Thanks @matmannion and @hans2520 for contribution.

**Comment by hans2520** [comment]
Thanks @matmannion for the quick turnaround! Verified issue is fixed in our projects with v5.3.4
